[package]
name = "log_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.9"
nom = "8.0.0"
serde = { version = "1.0.228", features = ["std", "derive"] }
serde_json = "1.0.145"
stopwords = "0.1.1"
